imports = [
    'cgmath::Vector2',
    'content::ComplexTile',
    'content::DoorState',
]

[components]
position = { type = 'Vector2<i32>' }
player = {}
floor = {}
collider = {}
solid = {}
opacity = { type = 'f64' }
enemy = {}
tile = { type = 'ComplexTile' }
tile_priority = { type = 'u8' }
door_state = { type = 'DoorState' }
