imports = [
    'cgmath::Vector2',
    'content::ComplexTile',
    'content::DoorState',
    'content::BehaviourType',
    'straight_line::FiniteAbsoluteLineTraverse',
    'schedule::ScheduleTicket',
]

[components]
position = { type = 'Vector2<i32>' }
player = {}
floor = {}
collider = {}
solid = {}
opacity = { type = 'f64' }
enemy = {}
tile = { type = 'ComplexTile' }
tile_priority = { type = 'u8' }
door_state = { type = 'DoorState' }
finite_trajectory = { type = 'FiniteAbsoluteLineTraverse' }
rain = {}
forgetable = {}
invisible = {}
inside = {}
splash = {}
turn_period = { type = 'u64' }
turn_ticket = { type = 'ScheduleTicket' }
behaviour_type = { type = 'BehaviourType' }
realtime = {}
vision_distance = { type = 'u32' }
