imports = [
    'cgmath::Vector2',
    'content::ComplexTile',
    'content::DoorState',
    'straight_line::FiniteAbsoluteLineTraverse',
]

[components]
position = { type = 'Vector2<i32>' }
player = {}
floor = {}
collider = {}
solid = {}
opacity = { type = 'f64' }
enemy = {}
tile = { type = 'ComplexTile' }
tile_priority = { type = 'u8' }
door_state = { type = 'DoorState' }
finite_trajectory = { type = 'FiniteAbsoluteLineTraverse' }
rain = {}
forgetable = {}
invisible = {}
inside = {}
splash = {}
