imports = [
    'cgmath::Vector2',
    'content::ComplexTile',
]

[components]
position = { name = 'Position', type = 'Vector2<i32>' }
player = { name = 'Player' }
floor = { name = 'Floor' }
solid = { name = 'Solid' }
opacity = { name = 'Opacity', type = 'f64' }
enemy = { name = 'Enemy' }
tile = { name = 'Tile', type = 'ComplexTile' }
tile_priority = { name = 'TilePriority', type = 'u8' }
