imports = [
    'cgmath::Vector2',
    'content::ComplexTile',
    'content::DoorState',
    'content::BehaviourType',
    'content::VeilStepInfo',
    'straight_line::FiniteAbsoluteLineTraverse',
    'straight_line::InfiniteAbsoluteLineTraverse',
    'schedule::ScheduleTicket',
]

[components]
position = { type = 'Vector2<i32>' }
player = {}
npc = {}
floor = {}
collider = {}
solid = {}
opacity = { type = 'f64' }
enemy = {}
tile = { type = 'ComplexTile' }
tile_priority = { type = 'u8' }
door_state = { type = 'DoorState' }
finite_trajectory = { type = 'FiniteAbsoluteLineTraverse' }
rain = {}
forgetable = {}
invisible = {}
inside = {}
splash = {}
turn_period = { type = 'u64' }
turn_ticket = { type = 'ScheduleTicket' }
behaviour_type = { type = 'BehaviourType' }
realtime = {}
realtime_period = { type = 'u64' }
vision_distance = { type = 'u32' }
infinite_trajectory = { type = 'InfiniteAbsoluteLineTraverse' }
door_opener = {}
bullet = {}
shootable = {}
omniscient = {}
veil_slot = {}
veil_current = {}
veil_next = {}
veil_change = {}
page = {}
veil_step_info = { type = 'VeilStepInfo' }
