imports = [
    'cgmath::Vector2',
]

position_component = 'position'

[fields]
opacity_total = { component = 'opacity', aggregate = 'f64_total' }
solid_count = { component = 'solid', aggregate = 'count' }
enemy_set = { component = 'enemy', aggregate = 'set' }
floor_set = { component = 'floor', aggregate = 'set' }
tile_set = { component = 'tile_priority', aggregate = 'set' }
opacity_count = { component = 'opacity', aggregate = 'count' }
opacity_set = { component = 'opacity', aggregate = 'set' }
