tile_size = 16

[overlays]
Blank = [0, 4]
Death = [1, 4]
VeilCurrent = [1, 4]
Veil = [2, 4]
VeilNext = [3, 4]
AimLineMid = [1, 6]
AimLineEnd = [0, 6]

[tiles.StoneFloor]
0 = [0, 0]
1 = [1, 0]

[tiles.WallFront]
1 = [0, 1]

[tiles.WallTop]
1 = [1, 1]

[tiles.Player]
1 = [0, 2]

[tiles.Undead]
1 = [1, 2]

[tiles.SuperUndead]
1 = [2, 2]

[tiles.Rain]
3 = [0, 3]

[tiles.Splash]
3 = [1, 3]

[tiles.OpenDoorTop]
2 = [1, 5]

[tiles.ClosedDoorTop]
2 = [0, 5]

[tiles.OpenDoorFront]
2 = [3, 5]

[tiles.ClosedDoorFront]
2 = [2, 5]

[tiles.Bullet]
2 = [0, 7]

[tiles.Page]
2 = [0, 8]
