imports = []

position_component = 'position'

[fields]
opacity_total = { component = 'opacity', aggregate = 'f64_total' }
solid_count = { component = 'solid', aggregate = 'count' }
enemy_set = { component = 'enemy', aggregate = 'set' }
npc_set = { component = 'npc', aggregate = 'set' }
floor_set = { component = 'floor', aggregate = 'set' }
tile_set = { component = 'tile_priority', aggregate = 'set' }
opacity_count = { component = 'opacity', aggregate = 'count' }
opacity_set = { component = 'opacity', aggregate = 'set' }
door_set = { component = 'door_state', aggregate = 'set' }
tile_change = { component = 'tile', aggregate = 'void' }
inside_count = { component = 'inside', aggregate = 'count' }
player_count = { component = 'player', aggregate = 'count' }
shootable_set = { component = 'shootable', aggregate = 'set' }
veil_slot_set = { component = 'veil_slot', aggregate = 'set' }
veil_current_count = { component = 'veil_current', aggregate = 'count' }
veil_next_count = { component = 'veil_next', aggregate = 'count' }
page_set = { component = 'page', aggregate = 'set' }
low_tile_count = { component = 'low_tile', aggregate = 'count' }
tile_front_set = { component = 'tile_front', aggregate = 'set' }
